version: 0.2

phases:
  pre_build:
    commands:
      - cp -pr doc/blueprint/* .
      - npm install
  build:
    commands:
      - npm run test
  post_build:
    commands:
      - aws s3 ls

artifacts:
  files:
    - '**/*'
  base-directory: doc/blueprint
  discard-paths: no
